schema_version: 1

context:
  name: azure-appconfiguration
  version: "1.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 168e7b01b350f5d806a2d935a8ec3694c59c6394d5a1c409eb05fef0b56b1aa0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-core >=1.30.0
    - isodate >=0.6.1
    - typing_extensions >=4.6.0
tests:
  - python:
      imports:
        - azure.appconfiguration
        - azure.appconfiguration._generated
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft App Configuration Data Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/appconfiguration/azure-appconfiguration

extra:
  recipe-maintainers:
    - janjagusch
